// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Simulator.proto

package grpc;

public interface NetStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.NetStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.NShead head = 1;</code>
   * @return Whether the head field is set.
   */
  boolean hasHead();
  /**
   * <code>.grpc.NShead head = 1;</code>
   * @return The head.
   */
  NShead getHead();
  /**
   * <code>.grpc.NShead head = 1;</code>
   */
  NSheadOrBuilder getHeadOrBuilder();

  /**
   * <code>repeated .grpc.NSbody body = 2;</code>
   */
  java.util.List<NSbody>
      getBodyList();
  /**
   * <code>repeated .grpc.NSbody body = 2;</code>
   */
  NSbody getBody(int index);
  /**
   * <code>repeated .grpc.NSbody body = 2;</code>
   */
  int getBodyCount();
  /**
   * <code>repeated .grpc.NSbody body = 2;</code>
   */
  java.util.List<? extends NSbodyOrBuilder>
      getBodyOrBuilderList();
  /**
   * <code>repeated .grpc.NSbody body = 2;</code>
   */
  NSbodyOrBuilder getBodyOrBuilder(
      int index);
}
