// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Simulator.proto

package grpc;

/**
 * Protobuf type {@code grpc.NSbody}
 */
public final class NSbody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.NSbody)
    NSbodyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NSbody.newBuilder() to construct.
  private NSbody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NSbody() {
    dstIP_ = "";
    srcIP_ = "";
    nextIP_ = "";
    dstmask_ = "";
    srcmask_ = "";
    outInterface_ = "";
    inInterface_ = "";
    reserved_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new NSbody();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NSbody(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            startTime_ = input.readDouble();
            break;
          }
          case 17: {

            endTime_ = input.readDouble();
            break;
          }
          case 24: {

            packageCount_ = input.readInt32();
            break;
          }
          case 32: {

            byteCount_ = input.readInt32();
            break;
          }
          case 40: {

            protocolType_ = input.readInt32();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            dstIP_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            srcIP_ = s;
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            nextIP_ = s;
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            dstmask_ = s;
            break;
          }
          case 82: {
            String s = input.readStringRequireUtf8();

            srcmask_ = s;
            break;
          }
          case 88: {

            dstAS_ = input.readInt32();
            break;
          }
          case 96: {

            srcAS_ = input.readInt32();
            break;
          }
          case 106: {
            String s = input.readStringRequireUtf8();

            outInterface_ = s;
            break;
          }
          case 114: {
            String s = input.readStringRequireUtf8();

            inInterface_ = s;
            break;
          }
          case 120: {

            dstPort_ = input.readInt32();
            break;
          }
          case 128: {

            srcPort_ = input.readInt32();
            break;
          }
          case 136: {

            tos_ = input.readInt32();
            break;
          }
          case 146: {
            String s = input.readStringRequireUtf8();

            reserved_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Simulator.internal_static_grpc_NSbody_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Simulator.internal_static_grpc_NSbody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NSbody.class, Builder.class);
  }

  public static final int START_TIME_FIELD_NUMBER = 1;
  private double startTime_;
  /**
   * <code>double Start_time = 1;</code>
   * @return The startTime.
   */
  @Override
  public double getStartTime() {
    return startTime_;
  }

  public static final int END_TIME_FIELD_NUMBER = 2;
  private double endTime_;
  /**
   * <code>double End_time = 2;</code>
   * @return The endTime.
   */
  @Override
  public double getEndTime() {
    return endTime_;
  }

  public static final int PACKAGE_COUNT_FIELD_NUMBER = 3;
  private int packageCount_;
  /**
   * <code>int32 Package_count = 3;</code>
   * @return The packageCount.
   */
  @Override
  public int getPackageCount() {
    return packageCount_;
  }

  public static final int BYTE_COUNT_FIELD_NUMBER = 4;
  private int byteCount_;
  /**
   * <code>int32 Byte_count = 4;</code>
   * @return The byteCount.
   */
  @Override
  public int getByteCount() {
    return byteCount_;
  }

  public static final int PROTOCOL_TYPE_FIELD_NUMBER = 5;
  private int protocolType_;
  /**
   * <pre>
   *对应号
   * </pre>
   *
   * <code>int32 Protocol_type = 5;</code>
   * @return The protocolType.
   */
  @Override
  public int getProtocolType() {
    return protocolType_;
  }

  public static final int DST_IP_FIELD_NUMBER = 6;
  private volatile Object dstIP_;
  /**
   * <code>string Dst_IP = 6;</code>
   * @return The dstIP.
   */
  @Override
  public String getDstIP() {
    Object ref = dstIP_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dstIP_ = s;
      return s;
    }
  }
  /**
   * <code>string Dst_IP = 6;</code>
   * @return The bytes for dstIP.
   */
  @Override
  public com.google.protobuf.ByteString
      getDstIPBytes() {
    Object ref = dstIP_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dstIP_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SRC_IP_FIELD_NUMBER = 7;
  private volatile Object srcIP_;
  /**
   * <code>string Src_IP = 7;</code>
   * @return The srcIP.
   */
  @Override
  public String getSrcIP() {
    Object ref = srcIP_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      srcIP_ = s;
      return s;
    }
  }
  /**
   * <code>string Src_IP = 7;</code>
   * @return The bytes for srcIP.
   */
  @Override
  public com.google.protobuf.ByteString
      getSrcIPBytes() {
    Object ref = srcIP_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      srcIP_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEXT_IP_FIELD_NUMBER = 8;
  private volatile Object nextIP_;
  /**
   * <code>string Next_IP = 8;</code>
   * @return The nextIP.
   */
  @Override
  public String getNextIP() {
    Object ref = nextIP_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      nextIP_ = s;
      return s;
    }
  }
  /**
   * <code>string Next_IP = 8;</code>
   * @return The bytes for nextIP.
   */
  @Override
  public com.google.protobuf.ByteString
      getNextIPBytes() {
    Object ref = nextIP_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      nextIP_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DSTMASK_FIELD_NUMBER = 9;
  private volatile Object dstmask_;
  /**
   * <code>string Dstmask = 9;</code>
   * @return The dstmask.
   */
  @Override
  public String getDstmask() {
    Object ref = dstmask_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dstmask_ = s;
      return s;
    }
  }
  /**
   * <code>string Dstmask = 9;</code>
   * @return The bytes for dstmask.
   */
  @Override
  public com.google.protobuf.ByteString
      getDstmaskBytes() {
    Object ref = dstmask_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dstmask_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SRCMASK_FIELD_NUMBER = 10;
  private volatile Object srcmask_;
  /**
   * <code>string Srcmask = 10;</code>
   * @return The srcmask.
   */
  @Override
  public String getSrcmask() {
    Object ref = srcmask_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      srcmask_ = s;
      return s;
    }
  }
  /**
   * <code>string Srcmask = 10;</code>
   * @return The bytes for srcmask.
   */
  @Override
  public com.google.protobuf.ByteString
      getSrcmaskBytes() {
    Object ref = srcmask_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      srcmask_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DST_AS_FIELD_NUMBER = 11;
  private int dstAS_;
  /**
   * <code>int32 Dst_AS = 11;</code>
   * @return The dstAS.
   */
  @Override
  public int getDstAS() {
    return dstAS_;
  }

  public static final int SRC_AS_FIELD_NUMBER = 12;
  private int srcAS_;
  /**
   * <code>int32 Src_AS = 12;</code>
   * @return The srcAS.
   */
  @Override
  public int getSrcAS() {
    return srcAS_;
  }

  public static final int OUT_INTERFACE_FIELD_NUMBER = 13;
  private volatile Object outInterface_;
  /**
   * <code>string Out_interface = 13;</code>
   * @return The outInterface.
   */
  @Override
  public String getOutInterface() {
    Object ref = outInterface_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      outInterface_ = s;
      return s;
    }
  }
  /**
   * <code>string Out_interface = 13;</code>
   * @return The bytes for outInterface.
   */
  @Override
  public com.google.protobuf.ByteString
      getOutInterfaceBytes() {
    Object ref = outInterface_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      outInterface_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IN_INTERFACE_FIELD_NUMBER = 14;
  private volatile Object inInterface_;
  /**
   * <code>string In_interface = 14;</code>
   * @return The inInterface.
   */
  @Override
  public String getInInterface() {
    Object ref = inInterface_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      inInterface_ = s;
      return s;
    }
  }
  /**
   * <code>string In_interface = 14;</code>
   * @return The bytes for inInterface.
   */
  @Override
  public com.google.protobuf.ByteString
      getInInterfaceBytes() {
    Object ref = inInterface_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      inInterface_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DST_PORT_FIELD_NUMBER = 15;
  private int dstPort_;
  /**
   * <code>int32 Dst_port = 15;</code>
   * @return The dstPort.
   */
  @Override
  public int getDstPort() {
    return dstPort_;
  }

  public static final int SRC_PORT_FIELD_NUMBER = 16;
  private int srcPort_;
  /**
   * <code>int32 Src_port = 16;</code>
   * @return The srcPort.
   */
  @Override
  public int getSrcPort() {
    return srcPort_;
  }

  public static final int TOS_FIELD_NUMBER = 17;
  private int tos_;
  /**
   * <code>int32 Tos = 17;</code>
   * @return The tos.
   */
  @Override
  public int getTos() {
    return tos_;
  }

  public static final int RESERVED_FIELD_NUMBER = 18;
  private volatile Object reserved_;
  /**
   * <code>string Reserved = 18;</code>
   * @return The reserved.
   */
  @Override
  public String getReserved() {
    Object ref = reserved_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      reserved_ = s;
      return s;
    }
  }
  /**
   * <code>string Reserved = 18;</code>
   * @return The bytes for reserved.
   */
  @Override
  public com.google.protobuf.ByteString
      getReservedBytes() {
    Object ref = reserved_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      reserved_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startTime_ != 0D) {
      output.writeDouble(1, startTime_);
    }
    if (endTime_ != 0D) {
      output.writeDouble(2, endTime_);
    }
    if (packageCount_ != 0) {
      output.writeInt32(3, packageCount_);
    }
    if (byteCount_ != 0) {
      output.writeInt32(4, byteCount_);
    }
    if (protocolType_ != 0) {
      output.writeInt32(5, protocolType_);
    }
    if (!getDstIPBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, dstIP_);
    }
    if (!getSrcIPBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, srcIP_);
    }
    if (!getNextIPBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, nextIP_);
    }
    if (!getDstmaskBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, dstmask_);
    }
    if (!getSrcmaskBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, srcmask_);
    }
    if (dstAS_ != 0) {
      output.writeInt32(11, dstAS_);
    }
    if (srcAS_ != 0) {
      output.writeInt32(12, srcAS_);
    }
    if (!getOutInterfaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, outInterface_);
    }
    if (!getInInterfaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, inInterface_);
    }
    if (dstPort_ != 0) {
      output.writeInt32(15, dstPort_);
    }
    if (srcPort_ != 0) {
      output.writeInt32(16, srcPort_);
    }
    if (tos_ != 0) {
      output.writeInt32(17, tos_);
    }
    if (!getReservedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, reserved_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startTime_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, startTime_);
    }
    if (endTime_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, endTime_);
    }
    if (packageCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, packageCount_);
    }
    if (byteCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, byteCount_);
    }
    if (protocolType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, protocolType_);
    }
    if (!getDstIPBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, dstIP_);
    }
    if (!getSrcIPBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, srcIP_);
    }
    if (!getNextIPBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, nextIP_);
    }
    if (!getDstmaskBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, dstmask_);
    }
    if (!getSrcmaskBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, srcmask_);
    }
    if (dstAS_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, dstAS_);
    }
    if (srcAS_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, srcAS_);
    }
    if (!getOutInterfaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, outInterface_);
    }
    if (!getInInterfaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, inInterface_);
    }
    if (dstPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, dstPort_);
    }
    if (srcPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, srcPort_);
    }
    if (tos_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, tos_);
    }
    if (!getReservedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, reserved_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NSbody)) {
      return super.equals(obj);
    }
    NSbody other = (NSbody) obj;

    if (Double.doubleToLongBits(getStartTime())
        != Double.doubleToLongBits(
            other.getStartTime())) return false;
    if (Double.doubleToLongBits(getEndTime())
        != Double.doubleToLongBits(
            other.getEndTime())) return false;
    if (getPackageCount()
        != other.getPackageCount()) return false;
    if (getByteCount()
        != other.getByteCount()) return false;
    if (getProtocolType()
        != other.getProtocolType()) return false;
    if (!getDstIP()
        .equals(other.getDstIP())) return false;
    if (!getSrcIP()
        .equals(other.getSrcIP())) return false;
    if (!getNextIP()
        .equals(other.getNextIP())) return false;
    if (!getDstmask()
        .equals(other.getDstmask())) return false;
    if (!getSrcmask()
        .equals(other.getSrcmask())) return false;
    if (getDstAS()
        != other.getDstAS()) return false;
    if (getSrcAS()
        != other.getSrcAS()) return false;
    if (!getOutInterface()
        .equals(other.getOutInterface())) return false;
    if (!getInInterface()
        .equals(other.getInInterface())) return false;
    if (getDstPort()
        != other.getDstPort()) return false;
    if (getSrcPort()
        != other.getSrcPort()) return false;
    if (getTos()
        != other.getTos()) return false;
    if (!getReserved()
        .equals(other.getReserved())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + START_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getStartTime()));
    hash = (37 * hash) + END_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getEndTime()));
    hash = (37 * hash) + PACKAGE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getPackageCount();
    hash = (37 * hash) + BYTE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getByteCount();
    hash = (37 * hash) + PROTOCOL_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getProtocolType();
    hash = (37 * hash) + DST_IP_FIELD_NUMBER;
    hash = (53 * hash) + getDstIP().hashCode();
    hash = (37 * hash) + SRC_IP_FIELD_NUMBER;
    hash = (53 * hash) + getSrcIP().hashCode();
    hash = (37 * hash) + NEXT_IP_FIELD_NUMBER;
    hash = (53 * hash) + getNextIP().hashCode();
    hash = (37 * hash) + DSTMASK_FIELD_NUMBER;
    hash = (53 * hash) + getDstmask().hashCode();
    hash = (37 * hash) + SRCMASK_FIELD_NUMBER;
    hash = (53 * hash) + getSrcmask().hashCode();
    hash = (37 * hash) + DST_AS_FIELD_NUMBER;
    hash = (53 * hash) + getDstAS();
    hash = (37 * hash) + SRC_AS_FIELD_NUMBER;
    hash = (53 * hash) + getSrcAS();
    hash = (37 * hash) + OUT_INTERFACE_FIELD_NUMBER;
    hash = (53 * hash) + getOutInterface().hashCode();
    hash = (37 * hash) + IN_INTERFACE_FIELD_NUMBER;
    hash = (53 * hash) + getInInterface().hashCode();
    hash = (37 * hash) + DST_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getDstPort();
    hash = (37 * hash) + SRC_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getSrcPort();
    hash = (37 * hash) + TOS_FIELD_NUMBER;
    hash = (53 * hash) + getTos();
    hash = (37 * hash) + RESERVED_FIELD_NUMBER;
    hash = (53 * hash) + getReserved().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NSbody parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NSbody parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NSbody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NSbody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NSbody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NSbody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NSbody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NSbody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NSbody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NSbody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NSbody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NSbody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NSbody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.NSbody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.NSbody)
      NSbodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Simulator.internal_static_grpc_NSbody_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Simulator.internal_static_grpc_NSbody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NSbody.class, Builder.class);
    }

    // Construct using grpc.NSbody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      startTime_ = 0D;

      endTime_ = 0D;

      packageCount_ = 0;

      byteCount_ = 0;

      protocolType_ = 0;

      dstIP_ = "";

      srcIP_ = "";

      nextIP_ = "";

      dstmask_ = "";

      srcmask_ = "";

      dstAS_ = 0;

      srcAS_ = 0;

      outInterface_ = "";

      inInterface_ = "";

      dstPort_ = 0;

      srcPort_ = 0;

      tos_ = 0;

      reserved_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Simulator.internal_static_grpc_NSbody_descriptor;
    }

    @Override
    public NSbody getDefaultInstanceForType() {
      return NSbody.getDefaultInstance();
    }

    @Override
    public NSbody build() {
      NSbody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public NSbody buildPartial() {
      NSbody result = new NSbody(this);
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.packageCount_ = packageCount_;
      result.byteCount_ = byteCount_;
      result.protocolType_ = protocolType_;
      result.dstIP_ = dstIP_;
      result.srcIP_ = srcIP_;
      result.nextIP_ = nextIP_;
      result.dstmask_ = dstmask_;
      result.srcmask_ = srcmask_;
      result.dstAS_ = dstAS_;
      result.srcAS_ = srcAS_;
      result.outInterface_ = outInterface_;
      result.inInterface_ = inInterface_;
      result.dstPort_ = dstPort_;
      result.srcPort_ = srcPort_;
      result.tos_ = tos_;
      result.reserved_ = reserved_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NSbody) {
        return mergeFrom((NSbody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NSbody other) {
      if (other == NSbody.getDefaultInstance()) return this;
      if (other.getStartTime() != 0D) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0D) {
        setEndTime(other.getEndTime());
      }
      if (other.getPackageCount() != 0) {
        setPackageCount(other.getPackageCount());
      }
      if (other.getByteCount() != 0) {
        setByteCount(other.getByteCount());
      }
      if (other.getProtocolType() != 0) {
        setProtocolType(other.getProtocolType());
      }
      if (!other.getDstIP().isEmpty()) {
        dstIP_ = other.dstIP_;
        onChanged();
      }
      if (!other.getSrcIP().isEmpty()) {
        srcIP_ = other.srcIP_;
        onChanged();
      }
      if (!other.getNextIP().isEmpty()) {
        nextIP_ = other.nextIP_;
        onChanged();
      }
      if (!other.getDstmask().isEmpty()) {
        dstmask_ = other.dstmask_;
        onChanged();
      }
      if (!other.getSrcmask().isEmpty()) {
        srcmask_ = other.srcmask_;
        onChanged();
      }
      if (other.getDstAS() != 0) {
        setDstAS(other.getDstAS());
      }
      if (other.getSrcAS() != 0) {
        setSrcAS(other.getSrcAS());
      }
      if (!other.getOutInterface().isEmpty()) {
        outInterface_ = other.outInterface_;
        onChanged();
      }
      if (!other.getInInterface().isEmpty()) {
        inInterface_ = other.inInterface_;
        onChanged();
      }
      if (other.getDstPort() != 0) {
        setDstPort(other.getDstPort());
      }
      if (other.getSrcPort() != 0) {
        setSrcPort(other.getSrcPort());
      }
      if (other.getTos() != 0) {
        setTos(other.getTos());
      }
      if (!other.getReserved().isEmpty()) {
        reserved_ = other.reserved_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NSbody parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NSbody) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double startTime_ ;
    /**
     * <code>double Start_time = 1;</code>
     * @return The startTime.
     */
    @Override
    public double getStartTime() {
      return startTime_;
    }
    /**
     * <code>double Start_time = 1;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(double value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double Start_time = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      
      startTime_ = 0D;
      onChanged();
      return this;
    }

    private double endTime_ ;
    /**
     * <code>double End_time = 2;</code>
     * @return The endTime.
     */
    @Override
    public double getEndTime() {
      return endTime_;
    }
    /**
     * <code>double End_time = 2;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(double value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double End_time = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      
      endTime_ = 0D;
      onChanged();
      return this;
    }

    private int packageCount_ ;
    /**
     * <code>int32 Package_count = 3;</code>
     * @return The packageCount.
     */
    @Override
    public int getPackageCount() {
      return packageCount_;
    }
    /**
     * <code>int32 Package_count = 3;</code>
     * @param value The packageCount to set.
     * @return This builder for chaining.
     */
    public Builder setPackageCount(int value) {
      
      packageCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Package_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageCount() {
      
      packageCount_ = 0;
      onChanged();
      return this;
    }

    private int byteCount_ ;
    /**
     * <code>int32 Byte_count = 4;</code>
     * @return The byteCount.
     */
    @Override
    public int getByteCount() {
      return byteCount_;
    }
    /**
     * <code>int32 Byte_count = 4;</code>
     * @param value The byteCount to set.
     * @return This builder for chaining.
     */
    public Builder setByteCount(int value) {
      
      byteCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Byte_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearByteCount() {
      
      byteCount_ = 0;
      onChanged();
      return this;
    }

    private int protocolType_ ;
    /**
     * <pre>
     *对应号
     * </pre>
     *
     * <code>int32 Protocol_type = 5;</code>
     * @return The protocolType.
     */
    @Override
    public int getProtocolType() {
      return protocolType_;
    }
    /**
     * <pre>
     *对应号
     * </pre>
     *
     * <code>int32 Protocol_type = 5;</code>
     * @param value The protocolType to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolType(int value) {
      
      protocolType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *对应号
     * </pre>
     *
     * <code>int32 Protocol_type = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocolType() {
      
      protocolType_ = 0;
      onChanged();
      return this;
    }

    private Object dstIP_ = "";
    /**
     * <code>string Dst_IP = 6;</code>
     * @return The dstIP.
     */
    public String getDstIP() {
      Object ref = dstIP_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dstIP_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Dst_IP = 6;</code>
     * @return The bytes for dstIP.
     */
    public com.google.protobuf.ByteString
        getDstIPBytes() {
      Object ref = dstIP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dstIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Dst_IP = 6;</code>
     * @param value The dstIP to set.
     * @return This builder for chaining.
     */
    public Builder setDstIP(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dstIP_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Dst_IP = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDstIP() {
      
      dstIP_ = getDefaultInstance().getDstIP();
      onChanged();
      return this;
    }
    /**
     * <code>string Dst_IP = 6;</code>
     * @param value The bytes for dstIP to set.
     * @return This builder for chaining.
     */
    public Builder setDstIPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dstIP_ = value;
      onChanged();
      return this;
    }

    private Object srcIP_ = "";
    /**
     * <code>string Src_IP = 7;</code>
     * @return The srcIP.
     */
    public String getSrcIP() {
      Object ref = srcIP_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        srcIP_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Src_IP = 7;</code>
     * @return The bytes for srcIP.
     */
    public com.google.protobuf.ByteString
        getSrcIPBytes() {
      Object ref = srcIP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        srcIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Src_IP = 7;</code>
     * @param value The srcIP to set.
     * @return This builder for chaining.
     */
    public Builder setSrcIP(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      srcIP_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Src_IP = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrcIP() {
      
      srcIP_ = getDefaultInstance().getSrcIP();
      onChanged();
      return this;
    }
    /**
     * <code>string Src_IP = 7;</code>
     * @param value The bytes for srcIP to set.
     * @return This builder for chaining.
     */
    public Builder setSrcIPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      srcIP_ = value;
      onChanged();
      return this;
    }

    private Object nextIP_ = "";
    /**
     * <code>string Next_IP = 8;</code>
     * @return The nextIP.
     */
    public String getNextIP() {
      Object ref = nextIP_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nextIP_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Next_IP = 8;</code>
     * @return The bytes for nextIP.
     */
    public com.google.protobuf.ByteString
        getNextIPBytes() {
      Object ref = nextIP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nextIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Next_IP = 8;</code>
     * @param value The nextIP to set.
     * @return This builder for chaining.
     */
    public Builder setNextIP(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nextIP_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Next_IP = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextIP() {
      
      nextIP_ = getDefaultInstance().getNextIP();
      onChanged();
      return this;
    }
    /**
     * <code>string Next_IP = 8;</code>
     * @param value The bytes for nextIP to set.
     * @return This builder for chaining.
     */
    public Builder setNextIPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nextIP_ = value;
      onChanged();
      return this;
    }

    private Object dstmask_ = "";
    /**
     * <code>string Dstmask = 9;</code>
     * @return The dstmask.
     */
    public String getDstmask() {
      Object ref = dstmask_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dstmask_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Dstmask = 9;</code>
     * @return The bytes for dstmask.
     */
    public com.google.protobuf.ByteString
        getDstmaskBytes() {
      Object ref = dstmask_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dstmask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Dstmask = 9;</code>
     * @param value The dstmask to set.
     * @return This builder for chaining.
     */
    public Builder setDstmask(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dstmask_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Dstmask = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDstmask() {
      
      dstmask_ = getDefaultInstance().getDstmask();
      onChanged();
      return this;
    }
    /**
     * <code>string Dstmask = 9;</code>
     * @param value The bytes for dstmask to set.
     * @return This builder for chaining.
     */
    public Builder setDstmaskBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dstmask_ = value;
      onChanged();
      return this;
    }

    private Object srcmask_ = "";
    /**
     * <code>string Srcmask = 10;</code>
     * @return The srcmask.
     */
    public String getSrcmask() {
      Object ref = srcmask_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        srcmask_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Srcmask = 10;</code>
     * @return The bytes for srcmask.
     */
    public com.google.protobuf.ByteString
        getSrcmaskBytes() {
      Object ref = srcmask_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        srcmask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Srcmask = 10;</code>
     * @param value The srcmask to set.
     * @return This builder for chaining.
     */
    public Builder setSrcmask(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      srcmask_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Srcmask = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrcmask() {
      
      srcmask_ = getDefaultInstance().getSrcmask();
      onChanged();
      return this;
    }
    /**
     * <code>string Srcmask = 10;</code>
     * @param value The bytes for srcmask to set.
     * @return This builder for chaining.
     */
    public Builder setSrcmaskBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      srcmask_ = value;
      onChanged();
      return this;
    }

    private int dstAS_ ;
    /**
     * <code>int32 Dst_AS = 11;</code>
     * @return The dstAS.
     */
    @Override
    public int getDstAS() {
      return dstAS_;
    }
    /**
     * <code>int32 Dst_AS = 11;</code>
     * @param value The dstAS to set.
     * @return This builder for chaining.
     */
    public Builder setDstAS(int value) {
      
      dstAS_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Dst_AS = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearDstAS() {
      
      dstAS_ = 0;
      onChanged();
      return this;
    }

    private int srcAS_ ;
    /**
     * <code>int32 Src_AS = 12;</code>
     * @return The srcAS.
     */
    @Override
    public int getSrcAS() {
      return srcAS_;
    }
    /**
     * <code>int32 Src_AS = 12;</code>
     * @param value The srcAS to set.
     * @return This builder for chaining.
     */
    public Builder setSrcAS(int value) {
      
      srcAS_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Src_AS = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrcAS() {
      
      srcAS_ = 0;
      onChanged();
      return this;
    }

    private Object outInterface_ = "";
    /**
     * <code>string Out_interface = 13;</code>
     * @return The outInterface.
     */
    public String getOutInterface() {
      Object ref = outInterface_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        outInterface_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Out_interface = 13;</code>
     * @return The bytes for outInterface.
     */
    public com.google.protobuf.ByteString
        getOutInterfaceBytes() {
      Object ref = outInterface_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        outInterface_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Out_interface = 13;</code>
     * @param value The outInterface to set.
     * @return This builder for chaining.
     */
    public Builder setOutInterface(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      outInterface_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Out_interface = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutInterface() {
      
      outInterface_ = getDefaultInstance().getOutInterface();
      onChanged();
      return this;
    }
    /**
     * <code>string Out_interface = 13;</code>
     * @param value The bytes for outInterface to set.
     * @return This builder for chaining.
     */
    public Builder setOutInterfaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      outInterface_ = value;
      onChanged();
      return this;
    }

    private Object inInterface_ = "";
    /**
     * <code>string In_interface = 14;</code>
     * @return The inInterface.
     */
    public String getInInterface() {
      Object ref = inInterface_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        inInterface_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string In_interface = 14;</code>
     * @return The bytes for inInterface.
     */
    public com.google.protobuf.ByteString
        getInInterfaceBytes() {
      Object ref = inInterface_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        inInterface_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string In_interface = 14;</code>
     * @param value The inInterface to set.
     * @return This builder for chaining.
     */
    public Builder setInInterface(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inInterface_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string In_interface = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearInInterface() {
      
      inInterface_ = getDefaultInstance().getInInterface();
      onChanged();
      return this;
    }
    /**
     * <code>string In_interface = 14;</code>
     * @param value The bytes for inInterface to set.
     * @return This builder for chaining.
     */
    public Builder setInInterfaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inInterface_ = value;
      onChanged();
      return this;
    }

    private int dstPort_ ;
    /**
     * <code>int32 Dst_port = 15;</code>
     * @return The dstPort.
     */
    @Override
    public int getDstPort() {
      return dstPort_;
    }
    /**
     * <code>int32 Dst_port = 15;</code>
     * @param value The dstPort to set.
     * @return This builder for chaining.
     */
    public Builder setDstPort(int value) {
      
      dstPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Dst_port = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearDstPort() {
      
      dstPort_ = 0;
      onChanged();
      return this;
    }

    private int srcPort_ ;
    /**
     * <code>int32 Src_port = 16;</code>
     * @return The srcPort.
     */
    @Override
    public int getSrcPort() {
      return srcPort_;
    }
    /**
     * <code>int32 Src_port = 16;</code>
     * @param value The srcPort to set.
     * @return This builder for chaining.
     */
    public Builder setSrcPort(int value) {
      
      srcPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Src_port = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrcPort() {
      
      srcPort_ = 0;
      onChanged();
      return this;
    }

    private int tos_ ;
    /**
     * <code>int32 Tos = 17;</code>
     * @return The tos.
     */
    @Override
    public int getTos() {
      return tos_;
    }
    /**
     * <code>int32 Tos = 17;</code>
     * @param value The tos to set.
     * @return This builder for chaining.
     */
    public Builder setTos(int value) {
      
      tos_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Tos = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearTos() {
      
      tos_ = 0;
      onChanged();
      return this;
    }

    private Object reserved_ = "";
    /**
     * <code>string Reserved = 18;</code>
     * @return The reserved.
     */
    public String getReserved() {
      Object ref = reserved_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        reserved_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Reserved = 18;</code>
     * @return The bytes for reserved.
     */
    public com.google.protobuf.ByteString
        getReservedBytes() {
      Object ref = reserved_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reserved_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Reserved = 18;</code>
     * @param value The reserved to set.
     * @return This builder for chaining.
     */
    public Builder setReserved(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reserved_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Reserved = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearReserved() {
      
      reserved_ = getDefaultInstance().getReserved();
      onChanged();
      return this;
    }
    /**
     * <code>string Reserved = 18;</code>
     * @param value The bytes for reserved to set.
     * @return This builder for chaining.
     */
    public Builder setReservedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reserved_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.NSbody)
  }

  // @@protoc_insertion_point(class_scope:grpc.NSbody)
  private static final NSbody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NSbody();
  }

  public static NSbody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NSbody>
      PARSER = new com.google.protobuf.AbstractParser<NSbody>() {
    @Override
    public NSbody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NSbody(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NSbody> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NSbody> getParserForType() {
    return PARSER;
  }

  @Override
  public NSbody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

