# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Simulator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Simulator.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fSimulator.proto\x12\x04grpc\" \n\x0bSimResponse\x12\x11\n\tisArrived\x18\x01 \x01(\x08\"C\n\tNetStream\x12\x1a\n\x04head\x18\x01 \x01(\x0b\x32\x0c.grpc.NShead\x12\x1a\n\x04\x62ody\x18\x02 \x03(\x0b\x32\x0c.grpc.NSbody\"\xb3\x01\n\x06NShead\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x11\n\tSysUptime\x18\x03 \x01(\x01\x12\x11\n\tunix_secs\x18\x04 \x01(\x01\x12\x12\n\nunix_nsecs\x18\x05 \x01(\x01\x12\x15\n\rflow_sequence\x18\x06 \x01(\x03\x12\x13\n\x0b\x65ngine_type\x18\x07 \x01(\x05\x12\x11\n\tengine_id\x18\x08 \x01(\x05\x12\x10\n\x08reserved\x18\t \x01(\t\"\xd3\x02\n\x06NSbody\x12\x12\n\nStart_time\x18\x01 \x01(\x01\x12\x10\n\x08\x45nd_time\x18\x02 \x01(\x01\x12\x15\n\rPackage_count\x18\x03 \x01(\x05\x12\x12\n\nByte_count\x18\x04 \x01(\x05\x12\x15\n\rProtocol_type\x18\x05 \x01(\x05\x12\x0e\n\x06\x44st_IP\x18\x06 \x01(\t\x12\x0e\n\x06Src_IP\x18\x07 \x01(\t\x12\x0f\n\x07Next_IP\x18\x08 \x01(\t\x12\x0f\n\x07\x44stmask\x18\t \x01(\t\x12\x0f\n\x07Srcmask\x18\n \x01(\t\x12\x0e\n\x06\x44st_AS\x18\x0b \x01(\x05\x12\x0e\n\x06Src_AS\x18\x0c \x01(\x05\x12\x15\n\rOut_interface\x18\r \x01(\t\x12\x14\n\x0cIn_interface\x18\x0e \x01(\t\x12\x10\n\x08\x44st_port\x18\x0f \x01(\x05\x12\x10\n\x08Src_port\x18\x10 \x01(\x05\x12\x0b\n\x03Tos\x18\x11 \x01(\x05\x12\x10\n\x08Reserved\x18\x12 \x01(\t2G\n\x10SimulatorService\x12\x33\n\rsendNetStream\x12\x0f.grpc.NetStream\x1a\x11.grpc.SimResponseB\x02P\x01\x62\x06proto3'
)




_SIMRESPONSE = _descriptor.Descriptor(
  name='SimResponse',
  full_name='grpc.SimResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isArrived', full_name='grpc.SimResponse.isArrived', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=57,
)


_NETSTREAM = _descriptor.Descriptor(
  name='NetStream',
  full_name='grpc.NetStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='head', full_name='grpc.NetStream.head', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='grpc.NetStream.body', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=126,
)


_NSHEAD = _descriptor.Descriptor(
  name='NShead',
  full_name='grpc.NShead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='grpc.NShead.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='grpc.NShead.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SysUptime', full_name='grpc.NShead.SysUptime', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unix_secs', full_name='grpc.NShead.unix_secs', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unix_nsecs', full_name='grpc.NShead.unix_nsecs', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flow_sequence', full_name='grpc.NShead.flow_sequence', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='engine_type', full_name='grpc.NShead.engine_type', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='engine_id', full_name='grpc.NShead.engine_id', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reserved', full_name='grpc.NShead.reserved', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=308,
)


_NSBODY = _descriptor.Descriptor(
  name='NSbody',
  full_name='grpc.NSbody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Start_time', full_name='grpc.NSbody.Start_time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='End_time', full_name='grpc.NSbody.End_time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Package_count', full_name='grpc.NSbody.Package_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Byte_count', full_name='grpc.NSbody.Byte_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Protocol_type', full_name='grpc.NSbody.Protocol_type', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Dst_IP', full_name='grpc.NSbody.Dst_IP', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Src_IP', full_name='grpc.NSbody.Src_IP', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Next_IP', full_name='grpc.NSbody.Next_IP', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Dstmask', full_name='grpc.NSbody.Dstmask', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Srcmask', full_name='grpc.NSbody.Srcmask', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Dst_AS', full_name='grpc.NSbody.Dst_AS', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Src_AS', full_name='grpc.NSbody.Src_AS', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Out_interface', full_name='grpc.NSbody.Out_interface', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='In_interface', full_name='grpc.NSbody.In_interface', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Dst_port', full_name='grpc.NSbody.Dst_port', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Src_port', full_name='grpc.NSbody.Src_port', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Tos', full_name='grpc.NSbody.Tos', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Reserved', full_name='grpc.NSbody.Reserved', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=650,
)

_NETSTREAM.fields_by_name['head'].message_type = _NSHEAD
_NETSTREAM.fields_by_name['body'].message_type = _NSBODY
DESCRIPTOR.message_types_by_name['SimResponse'] = _SIMRESPONSE
DESCRIPTOR.message_types_by_name['NetStream'] = _NETSTREAM
DESCRIPTOR.message_types_by_name['NShead'] = _NSHEAD
DESCRIPTOR.message_types_by_name['NSbody'] = _NSBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimResponse = _reflection.GeneratedProtocolMessageType('SimResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIMRESPONSE,
  '__module__' : 'Simulator_pb2'
  # @@protoc_insertion_point(class_scope:grpc.SimResponse)
  })
_sym_db.RegisterMessage(SimResponse)

NetStream = _reflection.GeneratedProtocolMessageType('NetStream', (_message.Message,), {
  'DESCRIPTOR' : _NETSTREAM,
  '__module__' : 'Simulator_pb2'
  # @@protoc_insertion_point(class_scope:grpc.NetStream)
  })
_sym_db.RegisterMessage(NetStream)

NShead = _reflection.GeneratedProtocolMessageType('NShead', (_message.Message,), {
  'DESCRIPTOR' : _NSHEAD,
  '__module__' : 'Simulator_pb2'
  # @@protoc_insertion_point(class_scope:grpc.NShead)
  })
_sym_db.RegisterMessage(NShead)

NSbody = _reflection.GeneratedProtocolMessageType('NSbody', (_message.Message,), {
  'DESCRIPTOR' : _NSBODY,
  '__module__' : 'Simulator_pb2'
  # @@protoc_insertion_point(class_scope:grpc.NSbody)
  })
_sym_db.RegisterMessage(NSbody)


DESCRIPTOR._options = None

_SIMULATORSERVICE = _descriptor.ServiceDescriptor(
  name='SimulatorService',
  full_name='grpc.SimulatorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=652,
  serialized_end=723,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendNetStream',
    full_name='grpc.SimulatorService.sendNetStream',
    index=0,
    containing_service=None,
    input_type=_NETSTREAM,
    output_type=_SIMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMULATORSERVICE)

DESCRIPTOR.services_by_name['SimulatorService'] = _SIMULATORSERVICE

# @@protoc_insertion_point(module_scope)
