// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Simulator.proto

package grpc;

/**
 * Protobuf type {@code grpc.NetStream}
 */
public final class NetStream extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.NetStream)
    NetStreamOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NetStream.newBuilder() to construct.
  private NetStream(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NetStream() {
    body_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new NetStream();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NetStream(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            NShead.Builder subBuilder = null;
            if (head_ != null) {
              subBuilder = head_.toBuilder();
            }
            head_ = input.readMessage(NShead.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(head_);
              head_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              body_ = new java.util.ArrayList<NSbody>();
              mutable_bitField0_ |= 0x00000001;
            }
            body_.add(
                input.readMessage(NSbody.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        body_ = java.util.Collections.unmodifiableList(body_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Simulator.internal_static_grpc_NetStream_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Simulator.internal_static_grpc_NetStream_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NetStream.class, Builder.class);
  }

  public static final int HEAD_FIELD_NUMBER = 1;
  private NShead head_;
  /**
   * <code>.grpc.NShead head = 1;</code>
   * @return Whether the head field is set.
   */
  @Override
  public boolean hasHead() {
    return head_ != null;
  }
  /**
   * <code>.grpc.NShead head = 1;</code>
   * @return The head.
   */
  @Override
  public NShead getHead() {
    return head_ == null ? NShead.getDefaultInstance() : head_;
  }
  /**
   * <code>.grpc.NShead head = 1;</code>
   */
  @Override
  public NSheadOrBuilder getHeadOrBuilder() {
    return getHead();
  }

  public static final int BODY_FIELD_NUMBER = 2;
  private java.util.List<NSbody> body_;
  /**
   * <code>repeated .grpc.NSbody body = 2;</code>
   */
  @Override
  public java.util.List<NSbody> getBodyList() {
    return body_;
  }
  /**
   * <code>repeated .grpc.NSbody body = 2;</code>
   */
  @Override
  public java.util.List<? extends NSbodyOrBuilder>
      getBodyOrBuilderList() {
    return body_;
  }
  /**
   * <code>repeated .grpc.NSbody body = 2;</code>
   */
  @Override
  public int getBodyCount() {
    return body_.size();
  }
  /**
   * <code>repeated .grpc.NSbody body = 2;</code>
   */
  @Override
  public NSbody getBody(int index) {
    return body_.get(index);
  }
  /**
   * <code>repeated .grpc.NSbody body = 2;</code>
   */
  @Override
  public NSbodyOrBuilder getBodyOrBuilder(
      int index) {
    return body_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (head_ != null) {
      output.writeMessage(1, getHead());
    }
    for (int i = 0; i < body_.size(); i++) {
      output.writeMessage(2, body_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (head_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHead());
    }
    for (int i = 0; i < body_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, body_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NetStream)) {
      return super.equals(obj);
    }
    NetStream other = (NetStream) obj;

    if (hasHead() != other.hasHead()) return false;
    if (hasHead()) {
      if (!getHead()
          .equals(other.getHead())) return false;
    }
    if (!getBodyList()
        .equals(other.getBodyList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHead()) {
      hash = (37 * hash) + HEAD_FIELD_NUMBER;
      hash = (53 * hash) + getHead().hashCode();
    }
    if (getBodyCount() > 0) {
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBodyList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NetStream parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NetStream parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NetStream parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NetStream parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NetStream parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NetStream parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NetStream parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NetStream parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NetStream parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NetStream parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NetStream parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NetStream parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NetStream prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.NetStream}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.NetStream)
      NetStreamOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Simulator.internal_static_grpc_NetStream_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Simulator.internal_static_grpc_NetStream_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetStream.class, Builder.class);
    }

    // Construct using grpc.NetStream.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBodyFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (headBuilder_ == null) {
        head_ = null;
      } else {
        head_ = null;
        headBuilder_ = null;
      }
      if (bodyBuilder_ == null) {
        body_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        bodyBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Simulator.internal_static_grpc_NetStream_descriptor;
    }

    @Override
    public NetStream getDefaultInstanceForType() {
      return NetStream.getDefaultInstance();
    }

    @Override
    public NetStream build() {
      NetStream result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public NetStream buildPartial() {
      NetStream result = new NetStream(this);
      int from_bitField0_ = bitField0_;
      if (headBuilder_ == null) {
        result.head_ = head_;
      } else {
        result.head_ = headBuilder_.build();
      }
      if (bodyBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          body_ = java.util.Collections.unmodifiableList(body_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.body_ = body_;
      } else {
        result.body_ = bodyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NetStream) {
        return mergeFrom((NetStream)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NetStream other) {
      if (other == NetStream.getDefaultInstance()) return this;
      if (other.hasHead()) {
        mergeHead(other.getHead());
      }
      if (bodyBuilder_ == null) {
        if (!other.body_.isEmpty()) {
          if (body_.isEmpty()) {
            body_ = other.body_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBodyIsMutable();
            body_.addAll(other.body_);
          }
          onChanged();
        }
      } else {
        if (!other.body_.isEmpty()) {
          if (bodyBuilder_.isEmpty()) {
            bodyBuilder_.dispose();
            bodyBuilder_ = null;
            body_ = other.body_;
            bitField0_ = (bitField0_ & ~0x00000001);
            bodyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBodyFieldBuilder() : null;
          } else {
            bodyBuilder_.addAllMessages(other.body_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NetStream parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NetStream) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private NShead head_;
    private com.google.protobuf.SingleFieldBuilderV3<
        NShead, NShead.Builder, NSheadOrBuilder> headBuilder_;
    /**
     * <code>.grpc.NShead head = 1;</code>
     * @return Whether the head field is set.
     */
    public boolean hasHead() {
      return headBuilder_ != null || head_ != null;
    }
    /**
     * <code>.grpc.NShead head = 1;</code>
     * @return The head.
     */
    public NShead getHead() {
      if (headBuilder_ == null) {
        return head_ == null ? NShead.getDefaultInstance() : head_;
      } else {
        return headBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.NShead head = 1;</code>
     */
    public Builder setHead(NShead value) {
      if (headBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        head_ = value;
        onChanged();
      } else {
        headBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.NShead head = 1;</code>
     */
    public Builder setHead(
        NShead.Builder builderForValue) {
      if (headBuilder_ == null) {
        head_ = builderForValue.build();
        onChanged();
      } else {
        headBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.NShead head = 1;</code>
     */
    public Builder mergeHead(NShead value) {
      if (headBuilder_ == null) {
        if (head_ != null) {
          head_ =
            NShead.newBuilder(head_).mergeFrom(value).buildPartial();
        } else {
          head_ = value;
        }
        onChanged();
      } else {
        headBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.NShead head = 1;</code>
     */
    public Builder clearHead() {
      if (headBuilder_ == null) {
        head_ = null;
        onChanged();
      } else {
        head_ = null;
        headBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.NShead head = 1;</code>
     */
    public NShead.Builder getHeadBuilder() {
      
      onChanged();
      return getHeadFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.NShead head = 1;</code>
     */
    public NSheadOrBuilder getHeadOrBuilder() {
      if (headBuilder_ != null) {
        return headBuilder_.getMessageOrBuilder();
      } else {
        return head_ == null ?
            NShead.getDefaultInstance() : head_;
      }
    }
    /**
     * <code>.grpc.NShead head = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        NShead, NShead.Builder, NSheadOrBuilder>
        getHeadFieldBuilder() {
      if (headBuilder_ == null) {
        headBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            NShead, NShead.Builder, NSheadOrBuilder>(
                getHead(),
                getParentForChildren(),
                isClean());
        head_ = null;
      }
      return headBuilder_;
    }

    private java.util.List<NSbody> body_ =
      java.util.Collections.emptyList();
    private void ensureBodyIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        body_ = new java.util.ArrayList<NSbody>(body_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        NSbody, NSbody.Builder, NSbodyOrBuilder> bodyBuilder_;

    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public java.util.List<NSbody> getBodyList() {
      if (bodyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(body_);
      } else {
        return bodyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public int getBodyCount() {
      if (bodyBuilder_ == null) {
        return body_.size();
      } else {
        return bodyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public NSbody getBody(int index) {
      if (bodyBuilder_ == null) {
        return body_.get(index);
      } else {
        return bodyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public Builder setBody(
        int index, NSbody value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBodyIsMutable();
        body_.set(index, value);
        onChanged();
      } else {
        bodyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public Builder setBody(
        int index, NSbody.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        body_.set(index, builderForValue.build());
        onChanged();
      } else {
        bodyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public Builder addBody(NSbody value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBodyIsMutable();
        body_.add(value);
        onChanged();
      } else {
        bodyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public Builder addBody(
        int index, NSbody value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBodyIsMutable();
        body_.add(index, value);
        onChanged();
      } else {
        bodyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public Builder addBody(
        NSbody.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        body_.add(builderForValue.build());
        onChanged();
      } else {
        bodyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public Builder addBody(
        int index, NSbody.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        body_.add(index, builderForValue.build());
        onChanged();
      } else {
        bodyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public Builder addAllBody(
        Iterable<? extends NSbody> values) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, body_);
        onChanged();
      } else {
        bodyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public Builder clearBody() {
      if (bodyBuilder_ == null) {
        body_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        bodyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public Builder removeBody(int index) {
      if (bodyBuilder_ == null) {
        ensureBodyIsMutable();
        body_.remove(index);
        onChanged();
      } else {
        bodyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public NSbody.Builder getBodyBuilder(
        int index) {
      return getBodyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public NSbodyOrBuilder getBodyOrBuilder(
        int index) {
      if (bodyBuilder_ == null) {
        return body_.get(index);  } else {
        return bodyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public java.util.List<? extends NSbodyOrBuilder>
         getBodyOrBuilderList() {
      if (bodyBuilder_ != null) {
        return bodyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(body_);
      }
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public NSbody.Builder addBodyBuilder() {
      return getBodyFieldBuilder().addBuilder(
          NSbody.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public NSbody.Builder addBodyBuilder(
        int index) {
      return getBodyFieldBuilder().addBuilder(
          index, NSbody.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.NSbody body = 2;</code>
     */
    public java.util.List<NSbody.Builder>
         getBodyBuilderList() {
      return getBodyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        NSbody, NSbody.Builder, NSbodyOrBuilder>
        getBodyFieldBuilder() {
      if (bodyBuilder_ == null) {
        bodyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            NSbody, NSbody.Builder, NSbodyOrBuilder>(
                body_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      return bodyBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.NetStream)
  }

  // @@protoc_insertion_point(class_scope:grpc.NetStream)
  private static final NetStream DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NetStream();
  }

  public static NetStream getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NetStream>
      PARSER = new com.google.protobuf.AbstractParser<NetStream>() {
    @Override
    public NetStream parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NetStream(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NetStream> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NetStream> getParserForType() {
    return PARSER;
  }

  @Override
  public NetStream getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

