// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Simulator.proto

package grpc;

public interface SimResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.SimResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isArrived = 1;</code>
   * @return The isArrived.
   */
  boolean getIsArrived();
}
